# Automatically generated by TopicTreeSpecPrinter(**kwargs).
# The kwargs were:
# - fileObj: TextIOWrapper
# - footer: '# End of topic tree definition. Note that application may l...'
# - indentStep: 4
# - treeDoc: None
# - width: 70


class engine:
    """
    UNDOCUMENTED: created as parent without specification
    """

    class answer:
        """
        UNDOCUMENTED: created as parent without specification
        """

        class sensor_temp:
            """
            UNDOCUMENTED: created without spec
            """
            
            def msgDataSpec(temp):
                """
                - temp: UNDOCUMENTED
                """

    class status:
        """

        """
        def msgDataSpec(text):
            """
            - text: UNDOCUMENTED
            """

class gui:
    """
    UNDOCUMENTED: created as parent without specification
    """

    class con:
        """
        UNDOCUMENTED: created as parent without specification
        """

        class connect_sensor:
            """
            UNDOCUMENTED: created without spec
            """
            
            def msgDataSpec(sensor_type, sensor_port):
                """
                - sensor_port: UNDOCUMENTED
                - sensor_type: UNDOCUMENTED
                """

# End of topic tree definition. Note that application may load
# more than one definitions provider.
